package cz.cvut.fel.pjv.semwork.peer_to_peer_chat.models.enums.event;

public enum EventType {
    SEND_PUBLIC_MESSAGE,
    PRIVATE_MESSAGE_SEND,
    PUBLIC_MESSAGE_RECEIVE,
    PRIVATE_MESSAGE_RECEIVE,
    DISCOVER,
    SEND_HELLO,
    PROGRAM_START,
    GET_MESSAGE_HISTORY,
    SEND_CONACK,
    SEND_CONREQ,
    GET_PEER_LIST,
    ADD_PEER,
    CONNECTION_REQUESTED,
    ADD_MESSAGE_TO_HISTORY,
    PROGRAM_END, HANDLE_PUBLIC_MESSAGE,
    ADD_PRIVATE_MESSAGE_TO_HISTORY,
    GET_LOCAL_PEER, IS_PEER_CONNECTED, GET_PEER, REMOVE_PEER, SEND_TTT_INVITE, START_TTT_GAME, TTT_STATUS_SEND, GET_PRIVATE_MESSAGE_HISTORY, GET_LOCAL_PEER_ID,
    SHOW_FATAL_ERROR, RECEIVE_TTT_STATUS, REFRESH_MESSAGE_HISTORY, ADD_MORE_MESSAGES, CONFIRM_RECEIVE_TTT_INVITE, CONFIRM_SEND_TTT_INVITE, RECEIVE_TTT_INVITE
}
